---
name: Devel-MemUsed
version: 0.01
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: returns how much memory as allocated since the Devel::MemUsed object construction
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  Contextual::Return: 0
  Devel::Mallinfo: 0
build_requires:
  Test::More: 0
provides:
  Devel::MemUsed:
    file: lib/Devel/MemUsed.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
